leftnav:
- identifier: 85289723-b2d0-45fa-9f08-61e0069a8d9a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 75466d41-d549-4d8e-8ee5-1d8a9ea3682d
  name: 'Session 1: Organizing a Recitation Section'
  url: /pages/session-1-organizing-a-recitation-section-to-promote-student-learning
  weight: 20
- identifier: 84e63ce2-acd5-44b2-a71a-07e8f7a4f6ab
  name: 'Session 2: Keeping Students Engaged'
  url: /pages/session-2-keeping-students-engaged
  weight: 30
- identifier: da029e60-7255-42f9-a3e6-0c8cb08973e8
  name: 'Session 3: Creating an Inclusive Classroom'
  url: /pages/session-3-creating-an-inclusive-classroom
  weight: 40
- identifier: 16428e24-4dca-449a-86e6-790a4a249b63
  name: 'Session 4: Providing Constructive, Equitable Feedback'
  url: /pages/session-4-providing-constructive-equitable-feedback
  weight: 50
- identifier: 010a645f-e0b6-465c-b6db-f538efd0b386
  name: 'Session 5: How Students Learn'
  url: /pages/session-5-how-students-learn
  weight: 60
